"""
Enterprise Report Exporter

M3.3

Exports research results to Markdown.

Future
------
V2.0
    PDF Export

V3.0
    DOCX Export

V4.0
    HTML Dashboard
"""

from pathlib import Path


class ReportExporter:
    """
    Enterprise Markdown Report Exporter.
    """

    def __init__(self):

        self.output_folder = Path(

            "research/final"

        )

        self.output_folder.mkdir(

            parents=True,

            exist_ok=True

        )

    # =====================================================
    # Public API
    # =====================================================

    def export(
        self,
        query: str,
        pages: list,
        filename: str = "report.md"
    ) -> str:
        """
        Export research results to Markdown.

        Returns
        -------
        str
            Markdown report content.
        """

        report = self._build_markdown(

            query,

            pages

        )

        output_file = self.output_folder / filename

        output_file.write_text(

            report,

            encoding="utf-8"

        )

        print(

            f"Report saved: {output_file}"

        )

        return report

    # =====================================================
    # Build Markdown
    # =====================================================

    def _build_markdown(
        self,
        query: str,
        pages: list
    ) -> str:

        lines = []

        lines.append("# Research Report\n")

        lines.append(f"## Topic\n\n{query}\n")

        lines.append(

            f"\nRetrieved **{len(pages)}** pages.\n"

        )

        lines.append("\n---\n")

        if not pages:

            lines.append(

                "\nNo research results available.\n"

            )

            return "".join(lines)

        for index, page in enumerate(

            pages,

            start=1

        ):

            lines.append(

                f"\n## {index}. {page['title']}\n"

            )

            lines.append(

                f"\n**URL**\n\n"

                f"{page['url']}\n"

            )

            lines.append(

                f"\n**Quality Score**\n\n"

                f"{page.get('quality_score',0)}\n"

            )

            lines.append(

                f"\n**Final Score**\n\n"

                f"{page.get('final_score',0)}\n"

            )

            lines.append(

                "\n**Summary**\n\n"

            )

            lines.append(

                page.get(

                    "summary",

                    "No summary available."

                )

            )

            lines.append("\n\n---\n")

        lines.append(

            "\nGenerated by Automotive Research Agent\n"

        )

        return "".join(lines)